---
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
notifications:
  email:
    on_success: always
    on_failure: always
script: make test
deploy:
  provider: pypi
  user: nrocco
  password:
    secure: Tv2DyKjS44TMBX/xfUjuT4diFrVvYo4428yIqwrE64yLEFCOxYis5ZSbmVjyyveaBcXR5d07dWdzWKcJX8wJeXanFlwRlz5VGGV3wNSQHRnT3M9JoaIH7/MGs6izDgun//KBXhKOZyQaYKUp3MaGtdi7BRsQ5rNo0NuYawNNdL4=
  on:
    tags: true
    branch: master
